# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import session.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(blank=True, db_index=True, max_length=30)),
                ('patient_id', models.IntegerField()),
                ('session_name', models.CharField(blank=True, db_index=True, max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=50)),
                ('xray', models.ImageField(blank=True, null=True, upload_to=session.models.upload_to)),
                ('bloodwork', models.ImageField(blank=True, null=True, upload_to=session.models.upload_to)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
