# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_remove_rawsession_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawsession',
            name='session_name',
            field=models.CharField(blank=True, db_index=True, max_length=25),
        ),
    ]
