# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import session.models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20170406_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawsession',
            name='shared_file',
            field=models.ImageField(blank=True, null=True, upload_to=session.models.upload_to),
        ),
    ]
