# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import session.models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_rawsession_shared_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawsession',
            name='shared_file',
            field=models.FileField(blank=True, null=True, upload_to=session.models.upload_to),
        ),
    ]
